include: package:effective_dart/analysis_options.yaml

analyzer:
  exclude:
    - "bin/cache/**"
    - "**.iconfig.dart"
    - "**.gr.dart"
    - "**/*.g.dart"

linter:
  rules:
    one_member_abstracts: false
